# -*- coding: utf-8 -*-
"""
Created on Thu Sep 29 00:09:39 2022

@author: Himanshu Tyagi

WARNING: Do not edit this file unless you know what you are doing.
"""


import serial
import os
from astropy import log
from astropy.coordinates import Angle, SkyCoord
from astropy.visualization import AsymmetricPercentileInterval
from regions import RectangleSkyRegion
from astropy.wcs import WCS
from astropy.io import fits
import matplotlib.pyplot as plt
from astroquery.skyview import SkyView
# SkyView.clear_cache()
from astropy.utils import data
# data.clear_download_cache()


import astropy.units as u
from astropy.nddata import Cutout2D
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sys
from PyQt5.QtWidgets import QDialog, QApplication, QPushButton, QVBoxLayout, QHeaderView, QTabWidget
from PyQt5.QtCore import pyqtSignal, pyqtSlot, QObject, QThread, QTimer
from matplotlib.backends.backend_qt5agg import FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT
from matplotlib.figure import Figure
from matplotlib.colors import LogNorm
from matplotlib.patches import Rectangle
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg, NavigationToolbar2QT as Navi
import sip
import pandas as pd
from scipy import ndimage
from astropy.visualization.interval import (PercentileInterval,
                                            AsymmetricPercentileInterval,
                                            ManualInterval, MinMaxInterval)

from astropy.visualization.stretch import (LinearStretch, SqrtStretch,
                                           PowerStretch, LogStretch,
                                           AsinhStretch)

from astropy.visualization.mpl_normalize import ImageNormalize
# import threading
import numpy as np
#%%
y = 70 # Vertical spacing for layout alignment in SkyView tab
tab4_y = -70 # Vertical spacing for layout alignment in Observations tab



class SerialReaderThread(QThread):
    received_data = pyqtSignal(str)
    def __init__(self, serial_port):
        super().__init__()
        self.serial_port = serial_port
    def run(self):
        while True:
            if self.serial_port.in_waiting > 0:
                received_data = self.serial_port.readline().decode().strip()
                self.received_data.emit(received_data)

class MatplotlibCanvas(FigureCanvasQTAgg):
	def __init__(self,parent=None, dpi = 120):
		self.fig = Figure(figsize=[10,10], dpi = dpi)
		super(MatplotlibCanvas,self).__init__(self.fig)


def simple_norm(data, stretch='linear', power=1.0, asinh_a=0.1, log_a=1000,
                min_cut=None, max_cut=None, min_percent=None, max_percent=None,
                percent=None, clip=True):

    if percent is not None:
        interval = PercentileInterval(percent)
    elif min_percent is not None or max_percent is not None:
        interval = AsymmetricPercentileInterval(min_percent or 0.,
                                                max_percent or 100.)
    elif min_cut is not None or max_cut is not None:
        interval = ManualInterval(min_cut, max_cut)
    else:
        interval = MinMaxInterval()

    if stretch == 'linear':
        stretch = LinearStretch()
    elif stretch == 'sqrt':
        stretch = SqrtStretch()
    elif stretch == 'power':
        stretch = PowerStretch(power)
    elif stretch == 'log':
        stretch = LogStretch(log_a)
    elif stretch == 'asinh':
        stretch = AsinhStretch(asinh_a)
    else:
        raise ValueError('Unknown stretch: {0}.'.format(stretch))

    vmin, vmax = interval.get_limits(data)

    return ImageNormalize(vmin=vmin, vmax=vmax, stretch=stretch, clip=clip)


def rotate(p, origin=(0, 0), degrees=0):
    angle = np.deg2rad(degrees)
    R = np.array([[np.cos(angle), -np.sin(angle)],
                  [np.sin(angle),  np.cos(angle)]])
    o = np.atleast_2d(origin)
    p = np.atleast_2d(p)
    return np.squeeze((R @ (p.T-o.T) + o.T).T)


class SkyViewWorker(QtCore.QThread):
    finished = QtCore.pyqtSignal(object, object)  # (hdu, wcs) or (None, None) on error

    def __init__(self, position, height, width, survey, parent=None):
        super().__init__(parent)
        self.position = position
        self.height = height
        self.width = width
        self.survey = survey

    def run(self):
        try:
            paths = SkyView.get_images(position=self.position, height=self.height, 
                                       width=self.width, survey=self.survey)
            hdu = paths[0][0]
            wcs = WCS(hdu.header).celestial
            self.finished.emit(hdu, wcs)
        except Exception as e:
            print("SkyView download error:", e)
            self.finished.emit(None, None)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1480, 1000)
        MainWindow.setFocusPolicy(QtCore.Qt.TabFocus)
        MainWindow.setStyleSheet("\n"
                                 "\n"
                                 "background-color: rgb(255,255,255);\n"
                                 "font: 14pt \"Times\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1480, 1000))
        self.tabWidget.setObjectName("tabWidget")
        # Theme selector (Light / Dark)
        self.theme_combo = QtWidgets.QComboBox(self.centralwidget)
        self.theme_combo.setGeometry(QtCore.QRect(1200, 15, 180, 31))
        self.theme_combo.setObjectName("theme_combo")
        self.theme_combo.addItems(["Light", "Dark"])
        self.theme_combo.setToolTip("Select application theme")
        # connect to MainWindow.apply_theme (MainWindow defines the handler)
        self.theme_combo.currentIndexChanged.connect(self.apply_theme)

        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(120, y+70*0, 131, 31))
        self.label.setObjectName("label")
        

        self.textEdit = QtWidgets.QLineEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(280, y+ 0*70, 371, 41))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setToolTip("Enter simbad searchable name")
        
        
        self.coords_label = QtWidgets.QLabel(self.tab_3)
        self.coords_label.setGeometry(QtCore.QRect(120, y+70*1, 131, 31))
        self.coords_label.setObjectName("coords_label")
        
        
        self.coords = QtWidgets.QLineEdit(self.tab_3)
        self.coords.setGeometry(QtCore.QRect(280, y+70*1, 371, 41))
        self.coords.setObjectName("coords")
        self.coords.setToolTip("Enter Coordinates (Optional, if Object name is given.)")
        
        
        self.field_rotation_value = QtWidgets.QLineEdit(self.tab_3)
        self.field_rotation_value.setGeometry(QtCore.QRect(280, y+70*2, 371, 41))
        self.field_rotation_value.setObjectName("field_rotation")
        self.field_rotation_value.setToolTip("Enter field rotation angle in degrees")
        
        
        self.field_rotation = QtWidgets.QLabel(self.tab_3)
        self.field_rotation.setGeometry(QtCore.QRect(120, y+70*2, 141, 31))
        self.field_rotation.setObjectName("field_rotation_value")
        
        
        self.label_filename = QtWidgets.QLabel(self.tab_3)
        self.label_filename.setGeometry(QtCore.QRect(120, y+70*3, 131, 31))
        self.label_filename.setObjectName("label")
        
        self.textEdit_filename = QtWidgets.QLineEdit(self.tab_3)
        self.textEdit_filename.setGeometry(QtCore.QRect(280, y+70*3, 250, 41))
        self.textEdit_filename.setObjectName("textEdit_filename")
        self.textEdit_filename.setToolTip("Optional (overrides Target Name)")

        self.file_upload = QtWidgets.QPushButton(self.tab_3)
        self.file_upload.setGeometry(QtCore.QRect(531, y+70*3, 120, 41))
        self.file_upload.setIcon( QtGui.QIcon("upload2.png"))
        self.file_upload.setObjectName("file_upload")
        self.file_upload.setToolTip("Upload a .fits file")
        
        
        self.target_list_fname = QtWidgets.QLabel(self.tab_3)
        self.target_list_fname.setGeometry(QtCore.QRect(120, y+70*4, 131, 31))
        self.target_list_fname.setObjectName("target_list_fname")
        
        self.target_list = QtWidgets.QLineEdit(self.tab_3)
        self.target_list.setGeometry(QtCore.QRect(280, y+70*4, 250, 41))
        self.target_list.setObjectName("target_list")
        self.target_list.setToolTip("Displays Targets in FOV (optional)")
        
        self.load_targets = QtWidgets.QPushButton(self.tab_3)
        self.load_targets.setGeometry(QtCore.QRect(531, y+70*4, 120, 41))
        self.load_targets.setIcon( QtGui.QIcon("csv.png"))
        self.load_targets.setObjectName("load_targets")
        self.load_targets.setToolTip("Load target list")  
        

        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(120, y+70*5, 180, 120))
        self.label_2.setObjectName("label_2")

        
        self.tableWidget = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget.setGeometry(QtCore.QRect(377, y+70*5, 275, 275))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)

        self.pushButton_5 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_5.setGeometry(QtCore.QRect(377, y+580+50, 275, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setToolTip("Plot slit configuration over sky image")

        # Cancel button for SkyView download (disabled by default)
        self.cancel_button = QtWidgets.QPushButton(self.tab_3)
        self.cancel_button.setGeometry(QtCore.QRect(377, y+70*9+50, 120, 41))
        self.cancel_button.setObjectName("cancel_button")
        self.cancel_button.setToolTip("Cancel SkyView download")
        self.cancel_button.setText("Cancel")
        self.cancel_button.setEnabled(False)
        self.cancel_button.clicked.connect(self.cancel_skyview)

        # Button to import slit settings (arcsec -> mm) to Engineers tab
        self.import_to_eng = QtWidgets.QPushButton(self.tab_3)
        self.import_to_eng.setGeometry(QtCore.QRect(500, y+70*9+50, 272-120, 41*2))
        self.import_to_eng.setObjectName("import_to_eng")
        self.import_to_eng.setToolTip("Export slit settings to Observations (convert arcsec -> mm)")
        self.import_to_eng.setText("Export to\nObservations")
        # Connect to MainWindow.import_slits_to_eng at runtime (MainWindow defines the handler)
        self.import_to_eng.clicked.connect(self.import_slits_to_eng)

        # Add loading animation label (make it a child of centralwidget)
        self.loading_label = QtWidgets.QLabel(self.centralwidget)
        self.loading_label.setGeometry(QtCore.QRect(900, y+70*2+50, 150, 150))  # Adjust as needed
        self.loading_label.setVisible(False)
        self.loading_label.setAttribute(QtCore.Qt.WA_TranslucentBackground, True)
        
        
        self.label_Temp = QtWidgets.QLabel(self.tab_3)
        self.label_Temp.setGeometry(QtCore.QRect(120, y+70*10+50, 131, 31))
        self.label_Temp.setObjectName("Temperature")
        
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber.setGeometry(QtCore.QRect(300, y+70*10+50, 161, 61))
        self.lcdNumber.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lcdNumber.setStyleSheet("color: rgb(255, 0, 0);")
        self.lcdNumber.setInputMethodHints(QtCore.Qt.ImhNoEditMenu)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdNumber.setProperty("intValue", 120)
        self.lcdNumber.setObjectName("lcdNumber")
        
        
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(750,y,700,700))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        
        MainWindow.setCentralWidget(self.tab_3)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.gridLayout.setObjectName("gridLayout")        
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spacerItem = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Minimum, 
                                                QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(self.spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        
        
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.spacerItem1 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Minimum, 
                                                 QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(self.spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.canv = MatplotlibCanvas(self)
        self.toolbar = Navi(self.canv,self.tab_3)
        self.horizontalLayout.addWidget(self.toolbar)
        
        self.pushButton_5.clicked.connect(self.plot_table)
        
        self.file_upload.clicked.connect(self.open_file)    
        self.load_targets.clicked.connect(self.open_target)    

        self.tabWidget.addTab(self.tab_3, "")


        ########   TAB ENG  #########################################################
        self.tab_4 = QtWidgets.QWidget()
        
        self.eng_ser_portno_fname = QtWidgets.QLabel(self.tab_4)
        self.eng_ser_portno_fname.setGeometry(QtCore.QRect(120, tab4_y+70*2, 151, 41))
        self.eng_ser_portno_fname.setObjectName("Serial port ID")
        
        self.eng_ser_port_no = QtWidgets.QLineEdit(self.tab_4)
        self.eng_ser_port_no.setGeometry(QtCore.QRect(377, tab4_y+70*2, 250, 41))
        self.eng_ser_port_no.setToolTip("Serial port ID input")
        
        
        self.eng_ser_port_fname = QtWidgets.QLabel(self.tab_4)
        self.eng_ser_port_fname.setGeometry(QtCore.QRect(120, tab4_y+70*3, 170, 41))
        self.eng_ser_port_fname.setObjectName("Serial port input")
        
        self.eng_ser_port = QtWidgets.QLineEdit(self.tab_4)
        self.eng_ser_port.setGeometry(QtCore.QRect(377, tab4_y+70*3, 250, 41))
        self.eng_ser_port.setObjectName("target_list")
        self.eng_ser_port.setToolTip("Serial port input")
        
        self.eng_ser_port_out = QtWidgets.QLabel(self.tab_4)
        self.eng_ser_port_out.setGeometry(QtCore.QRect(750, tab4_y+70*10, 200, 41))
        self.eng_ser_port_out.setObjectName("Serial port output")

        self.eng_ser_port_out_edit = QtWidgets.QTextEdit(self.tab_4, readOnly=True)
        self.eng_ser_port_out_edit.setGeometry(QtCore.QRect(750, tab4_y+70*10, 400, 200))
        self.eng_ser_port_out_edit.setObjectName("Serial port outputbox")

        self.eng_label_2 = QtWidgets.QLabel(self.tab_4)
        self.eng_label_2.setGeometry(QtCore.QRect(120, tab4_y+70*4, 180, 120))
        self.eng_label_2.setObjectName("label_2")

        
        self.eng_tableWidget = QtWidgets.QTableWidget(self.tab_4)
        self.eng_tableWidget.setGeometry(QtCore.QRect(377, tab4_y+70*4, 275, 275))
        self.eng_tableWidget.setObjectName("tableWidget")
        self.eng_tableWidget.setColumnCount(2)
        self.eng_tableWidget.setRowCount(5)


        item = QtWidgets.QTableWidgetItem()
        self.eng_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.eng_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.eng_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.eng_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.eng_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()

        self.eng_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.eng_tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.eng_tableWidget.verticalHeader().setStretchLastSection(True)
        self.eng_tableWidget.verticalHeader().setSectionResizeMode(QHeaderView.Stretch)
        
        self.eng_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.eng_tableWidget.setHorizontalHeaderItem(1, item)



        self.eng_pushButton_5 = QtWidgets.QPushButton(self.tab_4)
        self.eng_pushButton_5.setGeometry(QtCore.QRect(377, tab4_y+70*8, 275, 41))
        self.eng_pushButton_5.setObjectName("pushButton_5")
        self.eng_pushButton_5.setToolTip("Plot slit configuration over sky image")

        # Button to send imported slit configuration via serial port
        self.send_slits_button = QtWidgets.QPushButton(self.tab_4)
        self.send_slits_button.setGeometry(QtCore.QRect(377, tab4_y+70*9, 275, 41))
        self.send_slits_button.setObjectName("send_slits_button")
        self.send_slits_button.setToolTip("Send imported slit configuration via serial port")
        self.send_slits_button.setText("Configure Slits")
        # Connect to MainWindow.send_slit_config (defined in MainWindow)
        self.send_slits_button.clicked.connect(self.send_slit_config)

        # Filter wheel selector (5 filters) + send button
        # Wheel 1 selector + send button
        self.filter1_label = QtWidgets.QLabel(self.tab_4)
        self.filter1_label.setGeometry(QtCore.QRect(120, tab4_y+70*10, 150, 31))
        self.filter1_label.setObjectName("filter1_label")
        self.filter1_label.setText("Filter Wheel 1")
        self.filter1_combo = QtWidgets.QComboBox(self.tab_4)
        self.filter1_combo.setGeometry(QtCore.QRect(270+50, tab4_y+70*10, 120, 31))
        self.filter1_combo.setObjectName("filter1_combo")
        self.filter1_combo.addItems(["Filter1", "Filter2", "Filter3", "Filter4", "Filter5"])
        self.filter1_combo.setToolTip("Select filter for Wheel 1")
        # self.filter1_combo.setStyleSheet(
        #     "QComboBox { color: black; background-color: white; }"
        #     "QComboBox QAbstractItemView { background-color: white; color: black; selection-background-color: #d0e7ff; }"
        # )
        self.send_filter1_button = QtWidgets.QPushButton(self.tab_4)
        self.send_filter1_button.setGeometry(QtCore.QRect(400+50, tab4_y+70*10, 200, 31))
        self.send_filter1_button.setObjectName("send_filter1_button")
        self.send_filter1_button.setText("Send Filter for W1")
        self.send_filter1_button.setToolTip("Send selected filter for Wheel 1")
        self.send_filter1_button.clicked.connect(self.send_filter_wheel1)

        # Wheel 2 selector + send button
        self.filter2_label = QtWidgets.QLabel(self.tab_4)
        self.filter2_label.setGeometry(QtCore.QRect(120, tab4_y+70*11, 150, 31))
        self.filter2_label.setObjectName("filter2_label")
        self.filter2_label.setText("Filter Wheel 2")
        self.filter2_combo = QtWidgets.QComboBox(self.tab_4)
        self.filter2_combo.setGeometry(QtCore.QRect(270+50, tab4_y+70*11, 120, 31))
        self.filter2_combo.setObjectName("filter2_combo")
        self.filter2_combo.addItems(["Filter1", "Filter2", "Filter3", "Filter4", "Filter5"])
        self.filter2_combo.setToolTip("Select filter for Wheel 2")
        # self.filter2_combo.setStyleSheet(
        #     "QComboBox { color: black; background-color: white; }"
        #     "QComboBox QAbstractItemView { background-color: white; color: black; selection-background-color: #d0e7ff; }"
        # )
        self.send_filter2_button = QtWidgets.QPushButton(self.tab_4)
        self.send_filter2_button.setGeometry(QtCore.QRect(400+50, tab4_y+70*11, 200, 31))
        self.send_filter2_button.setObjectName("send_filter2_button")
        self.send_filter2_button.setText("Send Filter for W2")
        self.send_filter2_button.setToolTip("Send selected filter for Wheel 2")
        self.send_filter2_button.clicked.connect(self.send_filter_wheel2)        

        # Mirror / Grating 1 / Grating 2 selector + send button
        self.optics_label = QtWidgets.QLabel(self.tab_4)
        self.optics_label.setGeometry(QtCore.QRect(120, tab4_y+70*12, 170, 31))
        self.optics_label.setObjectName("optics_label")
        self.optics_label.setText("Grating / Mirror")

        self.optics_combo = QtWidgets.QComboBox(self.tab_4)
        self.optics_combo.setGeometry(QtCore.QRect(270+50, tab4_y+70*12, 160, 31))
        self.optics_combo.setObjectName("optics_combo")
        self.optics_combo.addItems(["Mirror", "Grating 1", "Grating 2"])
        self.optics_combo.setToolTip("Select Mirror or Grating")

        self.send_optics_button = QtWidgets.QPushButton(self.tab_4)
        self.send_optics_button.setGeometry(QtCore.QRect(440+50, tab4_y+70*12, 160, 31))
        self.send_optics_button.setObjectName("send_optics_button")
        self.send_optics_button.setText("Send Optic")
        self.send_optics_button.setToolTip("Send selected optic (mirror/grating) to hardware")
        # Connect to MainWindow.send_optic_selection (implemented in MainWindow)
        self.send_optics_button.clicked.connect(self.send_optic_selection)
        


        self.eng_gridLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.eng_gridLayoutWidget.setGeometry(QtCore.QRect(750,tab4_y,661,661))
        self.eng_gridLayoutWidget.setObjectName("gridLayoutWidget")
        
        self.eng_gridLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.eng_gridLayoutWidget.setGeometry(QtCore.QRect(750,tab4_y,661,661))
        self.eng_gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.eng_gridLayout = QtWidgets.QGridLayout(self.eng_gridLayoutWidget)
        self.eng_gridLayout.setContentsMargins(0, 0, 0, 0)
        self.eng_gridLayout.setObjectName("gridLayout")

        
        MainWindow.setCentralWidget(self.tab_4)
        self.eng_statusbar = QtWidgets.QStatusBar(MainWindow)
        self.eng_statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.eng_statusbar)

        self.eng_gridLayout.setObjectName("gridLayout")        
        self.eng_horizontalLayout = QtWidgets.QHBoxLayout()
        self.eng_horizontalLayout.setObjectName("horizontalLayout")
        self.eng_spacerItem = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.eng_horizontalLayout.addItem(self.eng_spacerItem)
        self.eng_gridLayout.addLayout(self.eng_horizontalLayout, 0, 0, 1, 1)
        
        
        self.eng_verticalLayout = QtWidgets.QVBoxLayout()
        self.eng_verticalLayout.setObjectName("verticalLayout")
        self.eng_spacerItem1 = QtWidgets.QSpacerItem(40, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.eng_verticalLayout.addItem(self.eng_spacerItem1)
        self.eng_gridLayout.addLayout(self.eng_verticalLayout, 1, 0, 1, 1)
        
        self.eng_canv = MatplotlibCanvas(self)
        self.eng_toolbar = Navi(self.eng_canv,self.tab_4)
        self.eng_horizontalLayout.addWidget(self.eng_toolbar)
        
        self.eng_pushButton_5.clicked.connect(self.eng_plot_table)
        self.eng_pushButton_5.clicked.connect(self.send_data)
        
        self.tabWidget.addTab(self.tab_4, "")
        #######################################################################
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Target name"))
        self.coords_label.setText(_translate("MainWindow", "Coordinates"))
        self.label_filename.setText(_translate("MainWindow", "File name"))
        self.label_2.setText(_translate("MainWindow", "Slit Configurations\n(Enter in arcsec)"))
        self.target_list_fname.setText(_translate("MainWindow", "Target list"))
        self.label_Temp.setText(_translate("MainWindow", "Temperature"))
        self.field_rotation.setText(_translate("MainWindow", "FOV Rotation"))

        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))

        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Slit Width"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Offset"))
        self.pushButton_5.setText(_translate("MainWindow", "Load FOV"))

        
        #######################################################################

        self.eng_label_2.setText(_translate("MainWindow", "Slit Configurations\n(Enter in mm)"))
        self.eng_ser_port_fname.setText(_translate("MainWindow", "Serial Port Input"))
        self.eng_ser_port_out.setText(_translate("MainWindow", "Serial Port Output"))
        self.eng_ser_port_out_edit.setText(_translate("MainWindow", "Serial Port Output"))
        self.eng_ser_portno_fname.setText(_translate("MainWindow", "Serial Port ID"))

        item = self.eng_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.eng_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.eng_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))

        item = self.eng_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.eng_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        
        item = self.eng_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "L Position"))
        item = self.eng_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Slit Width"))
        self.eng_pushButton_5.setText(_translate("MainWindow", "Slit Configuration Preview"))
        #@@
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Planning Tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Observation Setup"))
         



class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.threadpool = QtCore.QThreadPool()
        #self.worker_thread = WorkerThread()
        self.setupUi(self)

        self.serial_port = None

        # apply default theme (combo was created in setupUi)
        try:
            # set to the combo default and apply theme
            self.theme_combo.setCurrentIndex(0)
            self.apply_theme(self.theme_combo.currentIndex())
        except Exception:
            pass


        try:   
            pn = os.popen("ls /dev/ttyUSB*").read()[:-1]
            self.eng_ser_port_no.setText(pn)
            port_no = self.eng_ser_port_no.text()
            self.serial_port = serial.Serial(port_no, 9600)
            self.serial_thread = SerialReaderThread(self.serial_port)
            self.serial_thread.received_data.connect(self.receive_data)
            self.serial_thread.start()

        except:
             msg = QMessageBox()
             msg.setIcon(QMessageBox.Critical)
             msg.setText("Serial Port error")
             msg.setInformativeText(f"<html><head/><body><p><span style=\" color:black;\"> There is some issue in serial port communication.<br> Please try giving it permissions.<br> Use `sudo chmod o+rw /dev/ttyUSB*`</span></p><p><br/></p></body></html>")
             msg.setWindowTitle("Error")
             msg.exec_()

        self.loading_movie = QtGui.QMovie("././astro-loading.gif")
        self.loading_label.setMovie(self.loading_movie)


    def open_file(self):
            self.filename = QtWidgets.QFileDialog.getOpenFileName(None, 'Open File', '*.fits')
            print(self.filename[0])
            self.textEdit_filename.setText(self.filename[0])
        
    def open_target(self):
            self.filename = QtWidgets.QFileDialog.getOpenFileName(None, 'Open File', '*.csv')
            print(self.filename[0])
            self.target_list.setText(self.filename[0])


    def eng_open_file(self):
            self.filename = QtWidgets.QFileDialog.getOpenFileName(None, 'Open File', '*.fits')
            print(self.filename[0])
            self.eng_textEdit_filename.setText(self.filename[0])
        
    def eng_open_target(self):
            self.filename = QtWidgets.QFileDialog.getOpenFileName(None, 'Open File', '*.csv')
            print(self.filename[0])
            self.eng_target_list.setText(self.filename[0])

    def plot_table(self, vmin=None, vmid=None, vmax=None, pmin=0.25, pmax=99.75, 
                   stretch='linear', exponent=2):
        try:
            source_check = self.textEdit.text()
            coord_check = self.coords.text()
            file_name = self.textEdit_filename.text()
            
            if len(coord_check)!=0:
                coord_string = self.coords.text()
                try:
                    coord = SkyCoord(coord_string, frame="icrs")
                    
                except:
                    coord = SkyCoord(coord_string, frame="icrs", unit=(u.hourangle, u.deg))
                                    
            else:
                source = self.textEdit.text()                           
                coord = SkyCoord.from_name(source, frame = 'icrs')
                print('Coordinates of the requested objects are: ',coord.ra, coord.dec)
                #self.coords.setText(f"{str(coord.ra), str(coord.dec)}")
    
    
            if len(file_name) != 0:
                
                hdu = fits.open(file_name)

                if len(hdu)==1:
                        hdu = fits.open(file_name)[0]
                else:
                        hdu = fits.open(file_name)[1]
                
                wcs = WCS(hdu.header)
                
            elif len(file_name) !=0 and len(source_check)==0:
                # hdu = fits.open(file_name)[0]

                hdu = fits.open(file_name)

                if len(hdu)==1:
                        hdu = fits.open(file_name)[0]
                else:
                        hdu = fits.open(file_name)[1]
                        
                wcs = WCS(hdu.header).celestial
                coord_string = self.coords.text()
                coord = SkyCoord(coord_string, frame="icrs")
                
            if len(file_name) == 0 and (len(source_check) != 0 or len(coord_check) != 0):
                # Need to download from SkyView asynchronously
                if len(coord_check) != 0:
                    position = coord
                else:
                    source = self.textEdit.text()                           
                    coord = SkyCoord.from_name(source, frame = 'icrs')
                    print('Coordinates of the requested objects are: ',coord.ra, coord.dec)
                    position = coord #source
                self.pushButton_5.setEnabled(False)
                self.statusbar.showMessage("Downloading image from SkyView...")
                self.loading_label.setVisible(True)
                self.loading_label.raise_()
                self.loading_movie.start()
                self.cancel_button.setEnabled(True)
                QtWidgets.QApplication.processEvents()
                self.skyview_worker = SkyViewWorker(position, 14*u.arcmin, 14*u.arcmin, ['2MASS-K'])
                self.skyview_worker.finished.connect(self.on_skyview_downloaded)
                self.skyview_worker.start()
                return
            # print("In Main plot func: ",hdu, hdu.data)
            self._plot_with_hdu_wcs(hdu, wcs, coord, vmin, vmid, vmax, pmin, pmax, stretch, exponent)


            
        except:
            print("Object not found")
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Error")
            msg.setInformativeText('Object could not be found or slit configuration invalid')
            msg.setWindowTitle("Error")
            msg.exec_()
    
    def on_skyview_downloaded(self, hdu, wcs):
        self.loading_movie.stop()
        self.loading_label.setVisible(False)
        # Ensure cancel control state updated
        try:
            self.cancel_button.setEnabled(False)
        except Exception:
            pass
        QtWidgets.QApplication.processEvents()
        self.pushButton_5.setEnabled(True)
        self.statusbar.clearMessage()
        # if hdu is None or wcs is None:
        #     msg = QMessageBox()
        #     msg.setIcon(QMessageBox.Critical)
        #     msg.setText("Download Error")
        #     msg.setInformativeText('Failed to download image from SkyView')
        #     msg.setWindowTitle("Error")
        #     msg.exec_()
        #     return 
        if hdu is None or wcs is None:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Download Error")
            msg.setInformativeText('Failed to download image from SkyView')
            msg.setWindowTitle("Error")
            msg.exec_()
            return

        # Get coordinates from input fields
        coord_check = self.coords.text()
        if len(coord_check) != 0:
            try:
                coord = SkyCoord(coord_check, frame="icrs")
            except:
                coord = SkyCoord(coord_check, frame="icrs", unit=(u.hourangle, u.deg))
        else:
            source = self.textEdit.text()
            coord = SkyCoord.from_name(source, frame='icrs')

        self._plot_with_hdu_wcs(hdu, wcs, coord)
    
    def _plot_with_hdu_wcs(self, hdu, wcs, coord, vmin=None, vmid=None, vmax=None, pmin=0.25, pmax=99.75, 
                        stretch='linear', exponent=2):
        # try:
            # Remove old canvas and toolbar if they exist
            try:
                self.horizontalLayout.removeWidget(self.toolbar)
                self.verticalLayout.removeWidget(self.canv)
                sip.delete(self.toolbar)
                sip.delete(self.canv)
                self.toolbar = None         
                self.canv = None
                self.verticalLayout.removeItem(self.spacerItem1)
            except Exception as e:
                print(e)
                pass

            self.canv = MatplotlibCanvas(self)
            self.toolbar = Navi(self.canv, self.tab_3)
            self.horizontalLayout.addWidget(self.toolbar)
            self.verticalLayout.addWidget(self.canv)
            ax = self.canv.fig.add_subplot(111)

            min_auto = vmin is None
            max_auto = vmax is None

            if min_auto or max_auto:
                interval = AsymmetricPercentileInterval(pmin, pmax, n_samples=10000)
                try:
                    vmin_auto, vmax_auto = interval.get_limits(hdu.data)
                except (IndexError, TypeError):
                    vmin_auto = vmax_auto = 0
                vmin = vmin_auto
                vmax = vmax_auto

            # Prepare normalizer object
            if stretch == 'arcsinh':
                stretch = 'asinh'

            if stretch == 'log':
                if vmid is None:
                    if vmin < 0:
                        raise ValueError("When using a log stretch, if vmin < 0, then vmid has to be specified")
                    else:
                        vmid = 0.
                if vmin < vmid:
                    raise ValueError("When using a log stretch, vmin should be larger than vmid")
                log_a = (vmax - vmid) / (vmin - vmid)
                norm_kwargs = {'log_a': log_a}
            elif stretch == 'asinh':
                if vmid is None:
                    vmid = vmin - (vmax - vmin) / 30.
                asinh_a = (vmid - vmin) / (vmax - vmin)
                norm_kwargs = {'asinh_a': asinh_a}
            else:
                norm_kwargs = {}

            normalizer = simple_norm(hdu.data, stretch=stretch, power=exponent,
                                        min_cut=vmin, max_cut=vmax, clip=False,
                                        **norm_kwargs)

            # Adjust vmin/vmax if auto
            if stretch == 'linear':
                vmin = -0.1 * (vmax - vmin) + vmin
                vmax = 0.1 * (vmax - vmin) + vmax
            normalizer.vmin = vmin
            normalizer.vmax = vmax

            targetlist = self.target_list.text()

            if len(targetlist) != 0:
                try:
                    df = pd.read_csv(targetlist)
                    x, y = df['RA'], df['Dec']
                    target_coords = SkyCoord(x, y, unit='deg')
                    x, y = wcs.world_to_pixel(target_coords)
                except Exception as e:
                    print(f"Error reading target list: {e}")
                    x = y = None
            else:
                x = y = None

            # Determine rotation angle
            if len(self.field_rotation_value.text()) != 0:
                image_rotation = float(self.field_rotation_value.text())  # in degrees
            else:
                image_rotation = 0

            data = hdu.data
            if np.isnan(data).any():
                # Replace NaNs with median or 0
                data = np.nan_to_num(data, nan=np.nanmedian(data))
            rotated_array = ndimage.rotate(data, image_rotation, reshape=False, mode='constant', cval=np.nan)

            # Compute pixel coordinates for targets (if any)
            if x is not None and y is not None:
                # Get image center
                img_shape = hdu.data.shape
                center = np.array([img_shape[1]/2, img_shape[0]/2])
                # Stack x, y for rotation
                coords = np.vstack([x, y]).T
                # Rotate coordinates around image center (negative angle to match image rotation)
                coords_rot = rotate(coords, origin=center, degrees=-image_rotation)
                x_rot, y_rot = coords_rot[:,0], coords_rot[:,1]
            else:
                x_rot = y_rot = None

            

            fov_center_x = hdu.header['CRPIX1']
            fov_center_y = hdu.header['CRPIX2']
            # print(np.nanmax(rotated_array), rotated_array)
            ax.imshow(rotated_array, origin='lower', cmap="gist_earth", norm=normalizer)

            

            # Slit configuration
            fov_width = 3.1*60  # in arcsec
            delta_fov = 9.1  # in arcmin
            coord_fov = SkyCoord(coord.ra+(0/3600)*u.deg, coord.dec+(0)*u.arcsec)

            reg_detector = RectangleSkyRegion(coord_fov, width=delta_fov*u.arcmin, height=delta_fov*u.arcmin)
            pixel_region = reg_detector.to_pixel(wcs)
            artist = pixel_region.as_artist(color='gray', lw=1)
            ax.add_artist(artist)

            # Ensure the full reg_detector region is visible
            corners = pixel_region.corners
            xmin, xmax = np.min(corners[:, 0]), np.max(corners[:, 0])
            ymin, ymax = np.min(corners[:, 1]), np.max(corners[:, 1])

            # Add a margin (optional, e.g., 5% of width/height)
            xmargin = 0.05 * (xmax - xmin)
            ymargin = 0.05 * (ymax - ymin)

            ax.set_xlim(xmin - xmargin, xmax + xmargin)
            ax.set_ylim(ymin - ymargin, ymax + ymargin)

            sky_region = RectangleSkyRegion(coord_fov, width=fov_width*u.arcsec, height=delta_fov*u.arcmin)
            pixel_region = sky_region.to_pixel(wcs)
            artist = pixel_region.as_artist(color='w', lw=1)
            ax.add_artist(artist)

            if x is not None and y is not None:
                try:
                    ax.scatter(x_rot, y_rot, c='r', s=30, edgecolors='white', label='Targets')
                    ax.legend()

                except Exception as e:
                    print(f"Error plotting targets: {e}")
            

            c = ['r', 'tab:orange', 'yellow', 'lime', 'pink']
            slit_fov_check = []

            # for i in range(5):
            #     slit0_width = float(self.tableWidget.item(0+i, 0).text())
            #     delta_x0 = float(self.tableWidget.item(0+i, 1).text())
            #     coord_slit0 = SkyCoord(coord.ra+(delta_x0/3600)*u.deg, coord.dec+9.1*(2-i)/5*u.arcmin)
            #     sky_region = RectangleSkyRegion(coord_slit0, width=slit0_width*u.arcsec, height=9.1/5*u.arcmin)
            #     pixel_region = sky_region.to_pixel(wcs)
            #     artist = pixel_region.as_artist(color=c[i], lw=1)
            #     ax.add_artist(artist)
            #     ax.text(0.05, 0.9-i*0.05, f'Slit {i+1}', transform=ax.transAxes, c=c[i], weight="bold")
            #     if abs(delta_x0) > fov_width/2:
            #         slit_fov_check.append(delta_x0)

            for i in range(5):
                # robustly read slit width / offset from table (defaults to 0)
                try:
                    item_w = self.tableWidget.item(i, 0)
                    slit0_width = float(item_w.text()) if item_w is not None and item_w.text().strip() != "" else 0.0
                except Exception:
                    slit0_width = 0.0
                try:
                    item_off = self.tableWidget.item(i, 1)
                    delta_x0 = float(item_off.text()) if item_off is not None and item_off.text().strip() != "" else 0.0
                except Exception:
                    delta_x0 = 0.0

                # slit center in sky coords (offset in arcsec)
                coord_slit0 = SkyCoord(coord.ra + (delta_x0 / 3600.0) * u.deg,
                                       coord.dec + 9.1 * (2 - i) / 5.0 * u.arcmin)

                # For plotting, regions requires strictly positive width. If slit width == 0 treat as 'closed'
                # and draw a thin vertical marker instead of a filled rectangle.
                draw_width_arcsec = slit0_width if slit0_width > 0.0 else 1e-6
                sky_region = RectangleSkyRegion(coord_slit0,
                                                width=draw_width_arcsec * u.arcsec,
                                                height=(9.1 / 5.0) * u.arcmin)
                pixel_region = sky_region.to_pixel(wcs)

                # corners and center in pixel coordinates
                corners = pixel_region.corners
                xmin_r, xmax_r = np.min(corners[:, 0]), np.max(corners[:, 0])
                ymin_r, ymax_r = np.min(corners[:, 1]), np.max(corners[:, 1])
                xcen = 0.5 * (xmin_r + xmax_r)
                ycen = 0.5 * (ymin_r + ymax_r)

                if slit0_width > 0.0:
                    # normal filled rectangle for open slit
                    artist = pixel_region.as_artist(color=c[i], lw=1)
                    ax.add_artist(artist)
                else:
                    # closed slit -> draw a thin line at slit centre and label it 'Closed'
                    ax.plot([xcen, xcen], [ymin_r, ymax_r], color=c[i], lw=2)
                    ax.text(xcen + 5, ycen, "Closed", color=c[i], weight="bold", va='center')

                ax.text(0.05, 0.9 - i * 0.05, f'Slit {i+1}', transform=ax.transAxes, c=c[i], weight="bold")

                # check offset relative to FOV width (in arcsec)
                if abs(delta_x0) > fov_width / 2.0:
                    slit_fov_check.append(delta_x0)

            if len(slit_fov_check) > 0:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)
                msg.setText("Slit Out of FOV")
                msg.setInformativeText('At least one slit is out of FOV')
                msg.setWindowTitle("Error")
                msg.exec_()

            ax.set_xlabel('Pixel')
            ax.set_ylabel('Pixel')
            ax.set_title("2MASS Image (band Ks)")
            self.canv.draw()

        # except Exception as e:
        #     print("Object not found", e)
        #     msg = QMessageBox()
        #     msg.setIcon(QMessageBox.Critical)
        #     msg.setText("Error")
        #     msg.setInformativeText('Object could not be found or slit configuration invalid')
        #     msg.setWindowTitle("Error")
        #     msg.exec_()
    
        
    def eng_plot_table(self, vmin=None, vmid=None, vmax=None, pmin=0.25, pmax=99.75, 
                   stretch='linear', exponent=2):

        try:    
            try:
                self.eng_horizontalLayout.removeWidget(self.eng_toolbar)
                self.eng_verticalLayout.removeWidget(self.eng_canv)
                sip.delete(self.eng_toolbar)
                sip.delete(self.eng_canv)
                self.eng_toolbar = None         
                self.eng_canv = None
                self.eng_verticalLayout.removeItem(self.eng_spacerItem1)
                
            except Exception as e:
                print(e)
                pass
            
            self.eng_canv = MatplotlibCanvas(self)
            self.eng_toolbar = Navi(self.eng_canv,self.tab_4)
            self.eng_horizontalLayout.addWidget(self.eng_toolbar)
            self.eng_verticalLayout.addWidget(self.eng_canv)
            self.eng_canv.fig

            eng_ax = self.eng_canv.fig.add_subplot(111)
 
            fov_width = 8572 # in mm*100
 
            c = ['r', 'tab:orange', 'yellow', 'lime', 'pink']
            slit_fov_check = []
            
            for i in range(5):
                # map i=0..4 -> y positions 4..0 so Slit 1 is top and Slit 5 is bottom
                y_pos = 4 - i

                l_pos = float(self.eng_tableWidget.item(0+i, 0).text())*100
                slit0_width = l_pos
                delta_x0 = float(self.eng_tableWidget.item(0+i, 1).text())*100

                if delta_x0 == 0:
                    eng_ax.barh(y_pos, slit0_width, height=0.98, left=0, align='edge', color='gray', alpha=0.8)
                    eng_ax.barh(y_pos, (fov_width - (slit0_width + delta_x0)), height=0.98,
                                left=fov_width - (fov_width - (slit0_width + delta_x0)), align='edge',
                                color='gray', alpha=0.8)
                else:
                    eng_ax.barh(y_pos, slit0_width, height=0.98, left=0, align='edge', color=c[i], alpha=0.8)
                    eng_ax.barh(y_pos, (fov_width - (slit0_width + delta_x0)), height=0.98,
                                left=fov_width - (fov_width - (slit0_width + delta_x0)), align='edge',
                                color=c[i], alpha=0.8)

                eng_ax.set_xlim(0, fov_width)
                eng_ax.set_ylim(0, 5)
                # hide y-axis tick labels
                eng_ax.set_yticks([])
                eng_ax.tick_params(axis='y', which='both', labelleft=False)

                # place labels in axes coordinates but inverted so top shows Slit 1
                eng_ax.text(1.02, 0.1 + (4 - i) * 0.2, f'Slit {i+1}', transform=eng_ax.transAxes,
                            c=c[i], weight="bold")
                if slit0_width + (fov_width - (slit0_width + delta_x0)) > fov_width or l_pos > fov_width or l_pos < 0 or l_pos + delta_x0 > fov_width:
                    slit_fov_check.append(delta_x0)
            
            if len(slit_fov_check) > 0:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)
                msg.setText("Slit Configuration Error")
                msg.setInformativeText('Slit Out of FOV or Slit Collision Scenario')
                msg.setWindowTitle("Error")
                msg.exec_()

            eng_ax.set_xlabel('mm$\\times 100$')
            eng_ax.set_ylabel('Slit number')
            eng_ax.set_title("Slit Configuration")
            self.eng_canv.draw()

        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Slit Configuration Error")
            msg.setInformativeText('Invalid inputs')
            msg.setWindowTitle("Error")
            msg.exec_()
            
    def send_data(self):
        data_str = self.eng_ser_port.text().strip()
        if not data_str:
            self.eng_ser_port_out_edit.setHtml('<span style="color:red;">Serial Port connection failure: no data to send</span>')
            return

        if not hasattr(self, "serial_port") or self.serial_port is None:
            self.eng_ser_port_out_edit.setHtml('<span style="color:red;">Serial Port not available</span>')
            return
        try:
            self.serial_port.write(data_str.encode())
        except Exception as e:
            self.eng_ser_port_out_edit.setHtml(f'<span style="color:red;">Send failed: {e}</span>')

    def receive_data(self, received_data):
        self.eng_ser_port_out_edit.setText(f"<html><head/><body><p><span style=\" color:red;\">{received_data}</span></p><p><br/></p></body></html>")
        print(received_data)

    def send_slit_config(self):
        """Send the engineers table slit configuration over serial port.
        Format: 'SLITS;L1,W1;L2,W2;L3,W3;L4,W4;L5,W5\n' where L/W are mm (as shown in eng_tableWidget)."""
        # check serial port availability
        if not hasattr(self, "serial_port") or self.serial_port is None:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Serial Port Not Available")
            msg.setInformativeText("Serial port not connected. Cannot send slit configuration.")
            msg.setWindowTitle("Error")
            msg.exec_()
            return
        try:
            is_open = getattr(self.serial_port, "is_open", True)
            if not is_open:
                raise RuntimeError("Serial port is closed")
        except Exception:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Serial Port Error")
            msg.setInformativeText("Serial port not open or unavailable.")
            msg.setWindowTitle("Error")
            msg.exec_()
            return

        parts = []
        for i in range(5):
            try:
                item_L = self.eng_tableWidget.item(i, 0)
                item_W = self.eng_tableWidget.item(i, 1)
                L = float(item_L.text()) if item_L is not None and item_L.text().strip() != "" else 0.0
                W = float(item_W.text()) if item_W is not None and item_W.text().strip() != "" else 0.0
            except Exception:
                L = 0.0
                W = 0.0
            parts.append(f"{L:.6f},{W:.6f}")

        payload = "SLITS;" + ";".join(parts) + "\n"
        try:
            self.serial_port.write(payload.encode())
            self.statusbar.showMessage("Slit configuration sent", 3000)
        except Exception as e:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Send Failed")
            msg.setInformativeText(f"Failed to send slit configuration: {e}")
            msg.setWindowTitle("Error")
            msg.exec_()

    

    def send_filter_wheel1(self):
        """Send selected filter for Wheel 1 via serial port.
        Payload: 'FILTER;1;<index>;<name>\\n' where index is 1..5."""
        try:
            idx = self.filter1_combo.currentIndex()
            name = self.filter1_combo.currentText()
        except Exception:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Filter Selection Error")
            msg.setInformativeText("Wheel 1 selector missing.")
            msg.setWindowTitle("Warning")
            msg.exec_()
            return

        if not hasattr(self, "serial_port") or self.serial_port is None:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Serial Port Not Available")
            msg.setInformativeText("Serial port not connected. Cannot send filter selection.")
            msg.setWindowTitle("Error")
            msg.exec_()
            return
        try:
            if not getattr(self.serial_port, "is_open", True):
                raise RuntimeError("Serial port is closed")
        except Exception:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Serial Port Error")
            msg.setInformativeText("Serial port not open or unavailable.")
            msg.setWindowTitle("Error")
            msg.exec_()
            return

        payload = f"FILTER;1;{idx+1};{name}\n"
        try:
            self.serial_port.write(payload.encode())
            self.statusbar.showMessage(f"Sent Wheel1 filter {idx+1} ({name})", 3000)
        except Exception as e:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Send Failed")
            msg.setInformativeText(f"Failed to send filter command: {e}")
            msg.setWindowTitle("Error")
            msg.exec_()

    def send_filter_wheel2(self):
        """Send selected filter for Wheel 2 via serial port.
        Payload: 'FILTER;2;<index>;<name>\\n' where index is 1..5."""
        try:
            idx = self.filter2_combo.currentIndex()
            name = self.filter2_combo.currentText()
        except Exception:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Filter Selection Error")
            msg.setInformativeText("Wheel 2 selector missing.")
            msg.setWindowTitle("Warning")
            msg.exec_()
            return

        if not hasattr(self, "serial_port") or self.serial_port is None:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Serial Port Not Available")
            msg.setInformativeText("Serial port not connected. Cannot send filter selection.")
            msg.setWindowTitle("Error")
            msg.exec_()
            return
        try:
            if not getattr(self.serial_port, "is_open", True):
                raise RuntimeError("Serial port is closed")
        except Exception:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Serial Port Error")
            msg.setInformativeText("Serial port not open or unavailable.")
            msg.setWindowTitle("Error")
            msg.exec_()
            return

        payload = f"FILTER;2;{idx+1};{name}\n"
        try:
            self.serial_port.write(payload.encode())
            self.statusbar.showMessage(f"Sent Wheel2 filter {idx+1} ({name})", 3000)
        except Exception as e:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Send Failed")
            msg.setInformativeText(f"Failed to send filter command: {e}")
            msg.setWindowTitle("Error")
            msg.exec_()

    def send_optic_selection(self):
        """Send selected optic (mirror/grating) via serial port.
        Payload: 'OPTIC;<index>;<name>\\n' where index = 1:Mirror, 2:Grating1, 3:Grating2"""
        try:
            idx = self.optics_combo.currentIndex()
            name = self.optics_combo.currentText()
        except Exception:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("Optics Selection Error")
            msg.setInformativeText("Optics selector missing.")
            msg.setWindowTitle("Warning")
            msg.exec_()
            return

        if not hasattr(self, "serial_port") or self.serial_port is None:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Serial Port Not Available")
            msg.setInformativeText("Serial port not connected. Cannot send optics command.")
            msg.setWindowTitle("Error")
            msg.exec_()
            return
        try:
            if not getattr(self.serial_port, "is_open", True):
                raise RuntimeError("Serial port is closed")
        except Exception:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Serial Port Error")
            msg.setInformativeText("Serial port not open or unavailable.")
            msg.setWindowTitle("Error")
            msg.exec_()
            return

        payload = f"OPTIC;{idx+1};{name}\n"
        try:
            self.serial_port.write(payload.encode())
            self.statusbar.showMessage(f"Sent optic {idx+1} ({name})", 3000)
        except Exception as e:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Send Failed")
            msg.setInformativeText(f"Failed to send optic command: {e}")
            msg.setWindowTitle("Error")
            msg.exec_()

    def cancel_skyview(self):
        """Cancel a running SkyView download. Uses QThread.terminate() to stop the worker
        and performs UI cleanup. This is forceful but simple; it ensures the loading UI is cleared."""
        if hasattr(self, "skyview_worker") and self.skyview_worker.isRunning():
            try:
                # forcefully stop the worker thread
                self.skyview_worker.terminate()
                self.skyview_worker.wait(2000)
            except Exception as e:
                print("Error terminating SkyView worker:", e)
        # Cleanup UI regardless of whether termination succeeded
        try:
            self.loading_movie.stop()
            self.loading_label.setVisible(False)
            self.cancel_button.setEnabled(False)
            self.pushButton_5.setEnabled(True)
            self.statusbar.showMessage("SkyView download cancelled", 3000)
            QtWidgets.QApplication.processEvents()
        except Exception:
            pass

    
    
    def import_slits_to_eng(self):
        """Copy slit settings from astronomers table (arcsec) to engineers table (mm).

        Astronomer's table provides:
         - slit width (arcsec)
         - offset (arcsec) = center of slit relative to center of FOV (arcsec)

        Engineers table should receive:
         - L Position (mm) = position of left edge of slit measured from LEFT edge of engineer frame (mm)
         - Slit Width (mm) = slit width converted to mm

        Conversion:
         - 9.1 arcmin = 9.1 * 60 = 546 arcsec -> spans 85.72 mm on detector
         - mm per arcsec = 85.72 / 546 ≈ 0.157151 mm/arcsec
        """

        DEFAULT_SCALE = 85.72 / (9.1 * 60.0)  # ≈ 0.157151 mm/arcsec
        scale, ok = QtWidgets.QInputDialog.getDouble(self, "Conversion scale",
                                                     "mm per arcsec:", DEFAULT_SCALE, 0.0, 1e9, 6)
        if not ok:
             return

        # engineer fov parameters (consistent with eng_plot_table)
        fov_width_plot_units = 8572          # mm * 100 (as used in eng_plot_table)
        fov_width_mm = fov_width_plot_units / 100.0
        fov_center_mm = fov_width_mm / 2.0   # center in mm corresponds to zero offset in astronomer's frame

        # Read each row from astronomers table, compute left edge and width in mm,
        # and write into engineers table.
        for i in range(5):
            # read slit width (arcsec)
            try:
                item_w_arc = self.tableWidget.item(i, 0)
                w_arc = float(item_w_arc.text()) if item_w_arc is not None and item_w_arc.text().strip() != "" else 0.0
            except Exception:
                w_arc = 0.0

            # read offset (arcsec) - center offset from FOV center (positive -> to the right)
            try:
                item_off_arc = self.tableWidget.item(i, 1)
                off_arc = float(item_off_arc.text()) if item_off_arc is not None and item_off_arc.text().strip() != "" else 0.0
            except Exception:
                off_arc = 0.0

            # convert sizes to mm
            width_mm = w_arc * scale
            off_mm = off_arc * scale *(-1)  # invert offset sign: astronomers +ve = right, engineers +ve = left
            # off_mm = off_arc * scale  # astronomer's zero at FOV center -> engineer center = fov_center_mm

            # determine left edge position in engineer frame (mm measured from LEFT edge)
            # center position (mm) + offset (mm) gives slit center in engineer frame,
            # subtract half the width to get left edge.
            left_mm = fov_center_mm + off_mm - (width_mm / 2.0)

            # clamp to sensible range (optional) - keep within [0, fov_width_mm]
            # left_mm = max(0.0, min(left_mm, fov_width_mm - width_mm))

            # store in engineers table: column 0 = L Position (mm), column 1 = Slit Width (mm)
            item_left = QtWidgets.QTableWidgetItem(f"{left_mm:.6f}")
            item_width = QtWidgets.QTableWidgetItem(f"{width_mm:.6f}")
            self.eng_tableWidget.setItem(i, 0, item_left)
            self.eng_tableWidget.setItem(i, 1, item_width)

        # switch to engineers tab and notify user briefly
        try:
            self.tabWidget.setCurrentWidget(self.tab_4)
        except Exception:
            pass
        self.statusbar.showMessage("Imported slit settings to Engineers (arcsec → mm). L Position is left edge from left of FOV.", 3000)

    def apply_theme(self, index):
        """Apply theme selected in the theme_combo. index 0 = Light, 1 = Dark."""
        name = self.theme_combo.currentText() if hasattr(self, "theme_combo") else ("Light" if index == 0 else "Dark")
        if name.lower().startswith("dark"):
            self.apply_dark_theme()
        else:
            self.apply_light_theme()

    def apply_light_theme(self):
        qapp = QtWidgets.QApplication.instance()
        # Clear any widget-level stylesheet that may override application stylesheet
        try:
            self.setStyleSheet("")
        except Exception:
            pass
        qapp.setStyleSheet("""
        QWidget { background-color: #ffffff; color: #000000; font-family: Times; font-size: 14pt; }
        QLineEdit, QComboBox, QTableWidget, QTextEdit { background-color: #ffffff; color: #000000; selection-background-color: #cce4ff; }
        QPushButton { background-color: #f0f0f0; color: #000000; border: 1px solid #bdbdbd; padding: 4px; }
        QTabWidget::pane { background: #ffffff; }
        QStatusBar { background: #f0f0f0; color: #000000; }
        QComboBox QAbstractItemView { background-color: #ffffff; color: #000000; selection-background-color: #d0e7ff; }
        """)
        # Matplotlib style for light theme
        try:
            plt.style.use('default')
        except Exception:
            pass
        # Redraw canvases if present so mpl theme takes effect
        try:
            if hasattr(self, "canv") and self.canv:
                self.canv.draw()
        except Exception:
            pass
        try:
            if hasattr(self, "eng_canv") and self.eng_canv:
                self.eng_canv.draw()
        except Exception:
            pass

    def apply_dark_theme(self):
        qapp = QtWidgets.QApplication.instance()
        # Clear any widget-level stylesheet first so application stylesheet can take effect
        try:
            self.setStyleSheet("")
        except Exception:
            pass
        # Use a dark navy background for the window and readable text colors
        DARK_BG = "#0b1f3a"   # dark navy
        CONTROL_BG = "#17263a"  # slightly lighter for controls
        qapp.setStyleSheet(f"""
        QWidget {{ background-color: {DARK_BG}; color: #eaeaea; font-family: Times; font-size: 14pt; }}
        QLineEdit, QComboBox, QTableWidget, QTextEdit {{ background-color: {CONTROL_BG}; color: #eaeaea; selection-background-color: #2b6aa0; }}
        QPushButton {{ background-color: #1f4e7a; color: #ffffff; border: 1px solid #0b1f3a; padding: 4px; }}
        QTabWidget::pane {{ background: {DARK_BG}; }}
        QStatusBar {{ background: #071427; color: #eaeaea; }}
        QComboBox QAbstractItemView {{ background-color: {CONTROL_BG}; color: #eaeaea; selection-background-color: #2b6aa0; }}
        """)
        # Ensure main window background uses the same dark navy (overrides any earlier MainWindow stylesheet)
        try:
            self.setStyleSheet(f"QMainWindow {{ background-color: {DARK_BG}; }}")
        except Exception:
            pass
        # Matplotlib dark style
        try:
            plt.style.use('dark_background')
        except Exception:
            pass
        # Redraw canvases so matplotlib picks up dark style
        try:
            if hasattr(self, "canv") and self.canv:
                # set facecolor to transparent so underlying widget bg shows through
                self.canv.fig.set_facecolor('none')
                for ax in self.canv.fig.axes:
                    ax.set_facecolor(DARK_BG)
                self.canv.draw()
        except Exception:
            pass
        try:
            if hasattr(self, "eng_canv") and self.eng_canv:
                self.eng_canv.fig.set_facecolor('none')
                for ax in self.eng_canv.fig.axes:
                    ax.set_facecolor(DARK_BG)
                self.eng_canv.draw()
        except Exception:
            pass



    
class WorkerThread(QtCore.QThread):

    job_done = QtCore.pyqtSignal('QString')

    def __init__(self, parent=None):
        super(WorkerThread, self).__init__(parent)
        self.gui_text = None

    def do_work(self):
        source_check = "SSTc2d J034432.0+321143"
        coord_check = ""
        if len(coord_check) != 0:        
            paths = SkyView.get_images(position=coord_check, height=10*u.arcmin,  width=10*u.arcmin,
                                    survey=['2MASS-K'])
        else:
            paths = SkyView.get_images(position=source_check, height=10*u.arcmin,  width=10*u.arcmin,
                                    survey=['2MASS-K'])
        self.job_done.emit(paths[0])

    def run(self):
        self.do_work()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())